### ISSUE TITLE
Doesn't work with Python 3.6

### ISSUE THREAD

**Issue by fenak** [multiplechoice/scrapy-sqs-exporter#1]
Hi,

I'm playing with this library, and it doesn't work with Python 3 because of a few compatibility errors:
```
ImportError: cannot import name 'izip_longest'

AttributeError: 'dict' object has no attribute 'iteritems'

botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Entries, value: <filter object at 0x108d35780>, type: <class 'filter'>, valid types: <class 'list'>, <class 'tuple'>

NameError: name 'xrange' is not defined
```

I made some changes to make it work, I'll send a PR in case you are interested in having it merged in.
