### PR TITLE
Make code compatible with Python 3.6

### LINKED ISSUE #1: Doesn't work with Python 3.6
Hi,

I'm playing with this library, and it doesn't work with Python 3 because of a few compatibility errors:
```
ImportError: cannot import name 'izip_longest'

AttributeError: 'dict' object has no attribute 'iteritems'

botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Entries, value: <filter object at 0x108d35780>, type: <class 'filter'>, valid types: <class 'list'>, <class 'tuple'>

NameError: name 'xrange' is not defined
```

I made some changes to make it work, I'll send a PR in case you are interested in having it merged in.

### PR DESCRIPTION
**Pull request by fenak**
This fixes #1.

Basically using more `six` compatibility functions, as the library was already using it.

Tests are passing for me on Python 2.7.14 and 3.6.4 in macOS High Sierra.

### CODE REVIEW

**Comment by aodj** [comment]
Apologies for not getting to this sooner - I didn't receive any notifications from Github about issues or pull requests.
